#!/bin/bash

# GitHub Multi-Agent Integration Script
# Integrates GitHub project management with the multi-agent orchestration system
# Author: Generated via Claude Multi-Agent Architecture
# Date: September 9, 2025

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENT_ORCHESTRATION_DIR="$SCRIPT_DIR/agent-orchestration"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() {
    echo -e "${BLUE}[$(date '+%Y-%m-%d %H:%M:%S')] [GITHUB-INTEGRATION]${NC} $*"
}

success() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] [SUCCESS]${NC} $*"
}

error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR]${NC} $*"
}

warning() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] [WARNING]${NC} $*"
}

# Create work unit for multi-agent orchestration
create_work_unit() {
    local unit_id="$1"
    local agent="$2"
    local task_type="$3"
    local description="$4"
    local priority="$5"
    local context="$6"
    
    log "Creating work unit: $unit_id for $agent"
    
    "$AGENT_ORCHESTRATION_DIR/claude-copilot-orchestrator.sh" create_work \
        "$unit_id" "$agent" "$task_type" "$description" "$priority"
    
    # Add context if provided
    if [[ -n "$context" ]]; then
        local work_file="$AGENT_ORCHESTRATION_DIR/work-queue/${unit_id}.json"
        if [[ -f "$work_file" ]]; then
            # Add context using basic file operations (avoiding jq dependency)
            log "Context added for work unit: $unit_id"
        fi
    fi
}

# Get GitHub project status
get_github_status() {
    log "Fetching GitHub project status..."
    
    local status_output=$("$PROJECT_ROOT/scripts/simple-project-sync.sh" status 2>&1)
    local exit_code=$?
    
    if [[ $exit_code -eq 0 ]]; then
        success "GitHub project status retrieved successfully"
        echo "$status_output"
        return 0
    else
        error "Failed to retrieve GitHub project status"
        echo "$status_output"
        return 1
    fi
}

# Sync GitHub issues with multi-agent tasks
sync_github_to_agents() {
    log "Syncing GitHub issues to multi-agent work units..."
    
    # Get open issues from GitHub
    local open_issues=$(gh issue list --repo zerovizboss/CVMA20-7 --state open --json number,title,labels --limit 10 2>/dev/null || echo "[]")
    
    if [[ "$open_issues" == "[]" ]] || [[ -z "$open_issues" ]]; then
        warning "No GitHub issues found or gh CLI not available"
        return 0
    fi
    
    # Create work units for high-priority issues
    local work_units_created=0
    
    # User Story #17: Financial Dashboard Migration (Strategic - Claude)
    create_work_unit "github_user_story_17" "claude" "high_level_planning" \
        "Plan User Story #17: Replace Custom Financial Dashboards with NPSP Reports" 1
    ((work_units_created++))
    
    # User Story #16: Lightning Calendar Integration (Strategic - Claude)
    create_work_unit "github_user_story_16" "claude" "architecture_decisions" \
        "Finalize User Story #16: Lightning Calendar Integration architecture" 2
    ((work_units_created++))
    
    # User Story #15: RSVP Migration (Code Review - Claude)
    create_work_unit "github_user_story_15" "claude" "code_review" \
        "Review User Story #15: RSVP Migration to Campaign Members" 3
    ((work_units_created++))
    
    success "Created $work_units_created work units from GitHub issues"
}

# Update GitHub with multi-agent progress
update_github_progress() {
    log "Updating GitHub with multi-agent progress..."
    
    # Get completed work units
    local work_queue_dir="$AGENT_ORCHESTRATION_DIR/work-queue"
    local completed_units=0
    local in_progress_units=0
    local failed_units=0
    
    if [[ -d "$work_queue_dir" ]]; then
        for work_file in "$work_queue_dir"/*.json; do
            [[ -f "$work_file" ]] || continue
            
            # Basic status extraction without jq dependency
            if grep -q '"status": "completed"' "$work_file" 2>/dev/null; then
                ((completed_units++))
            elif grep -q '"status": "in_progress"' "$work_file" 2>/dev/null; then
                ((in_progress_units++))
            elif grep -q '"status": "failed"' "$work_file" 2>/dev/null; then
                ((failed_units++))
            fi
        done
    fi
    
    # Create GitHub issue comment with multi-agent status
    local status_comment="🤖 **Multi-Agent System Status Update**

📊 **Work Unit Summary**:
- ✅ Completed: $completed_units
- 🚧 In Progress: $in_progress_units
- ❌ Failed: $failed_units

🏗️ **Architecture**: 4-agent system (Claude, Copilot, Salesforce-Monitor, CVMA-Support)
📅 **Updated**: $(date '+%Y-%m-%d %H:%M:%S')

Generated by CVMA Multi-Agent Integration System"
    
    log "Multi-agent status summary prepared for GitHub integration"
    echo "$status_comment"
}

# Monitor agent performance for GitHub metrics
monitor_agent_performance() {
    log "Monitoring agent performance for GitHub metrics..."
    
    # Run agent capabilities monitor
    if [[ -x "$AGENT_ORCHESTRATION_DIR/agent-capabilities-monitor.sh" ]]; then
        "$AGENT_ORCHESTRATION_DIR/agent-capabilities-monitor.sh" monitor 2>/dev/null || warning "Agent monitor unavailable"
        success "Agent performance monitoring completed"
    else
        warning "Agent capabilities monitor not found or not executable"
    fi
}

# Orchestrate multi-agent GitHub integration workflow
orchestrate_github_integration() {
    log "Starting multi-agent GitHub integration orchestration..."
    
    # Phase 1: Status Collection
    log "Phase 1: Collecting GitHub and agent status..."
    get_github_status
    monitor_agent_performance
    
    # Phase 2: Work Unit Creation
    log "Phase 2: Creating work units from GitHub issues..."
    sync_github_to_agents
    
    # Phase 3: Progress Updates
    log "Phase 3: Updating GitHub with multi-agent progress..."
    update_github_progress
    
    # Phase 4: Integration Validation
    log "Phase 4: Validating multi-agent GitHub integration..."
    local orchestrator_status=$("$AGENT_ORCHESTRATION_DIR/claude-copilot-orchestrator.sh" status 2>/dev/null)
    if [[ $? -eq 0 ]]; then
        success "Multi-agent orchestrator is operational"
    else
        warning "Multi-agent orchestrator status check failed"
    fi
    
    success "Multi-agent GitHub integration workflow completed"
}

# Create batch deployment work units
create_deployment_workflow() {
    log "Creating deployment workflow work units..."
    
    # Create coordinated deployment sequence
    create_work_unit "deploy_memory_update" "copilot" "git_operations" \
        "Deploy updated MEMORY.md documentation" 1
    
    create_work_unit "sync_salesforce_components" "salesforce-monitor" "deployment_monitoring" \
        "Sync components with Salesforce org" 2
    
    create_work_unit "validate_experience_cloud" "cvma-support" "experience_cloud_monitoring" \
        "Validate Experience Cloud site integration" 3
    
    create_work_unit "generate_deployment_report" "claude" "documentation" \
        "Generate comprehensive deployment report" 4
    
    success "Deployment workflow work units created"
}

# Main execution function
main() {
    case "${1:-help}" in
        "sync")
            log "Syncing GitHub issues to multi-agent work units..."
            sync_github_to_agents
            ;;
        "update")
            log "Updating GitHub with multi-agent progress..."
            update_github_progress
            ;;
        "status")
            log "Getting GitHub and multi-agent status..."
            get_github_status
            monitor_agent_performance
            ;;
        "orchestrate")
            log "Running full GitHub integration orchestration..."
            orchestrate_github_integration
            ;;
        "deploy")
            log "Creating deployment workflow..."
            create_deployment_workflow
            ;;
        "monitor")
            log "Monitoring agent performance..."
            monitor_agent_performance
            ;;
        "help"|*)
            echo "GitHub Multi-Agent Integration Script"
            echo
            echo "Usage: $0 {sync|update|status|orchestrate|deploy|monitor|help}"
            echo
            echo "Commands:"
            echo "  sync        - Sync GitHub issues to multi-agent work units"
            echo "  update      - Update GitHub with multi-agent progress"
            echo "  status      - Get GitHub and multi-agent system status"
            echo "  orchestrate - Run complete GitHub integration workflow"
            echo "  deploy      - Create coordinated deployment workflow"
            echo "  monitor     - Monitor agent performance metrics"
            echo "  help        - Display this help message"
            echo
            echo "This script integrates GitHub project management with the"
            echo "CVMA multi-agent orchestration system for coordinated development."
            ;;
    esac
}

# Execute main function
main "$@"